### ISSUE TITLE
WLAN handle leak

### ISSUE THREAD

**Issue by FlowerCode** [xqq/softbank-autologin#1]
WLAN handle opened at
https://github.com/xqq/softbank-autologin/blob/e5eb50449ff54790c79592267ae9791dde092ab3/ssid_win32.cpp#L24
was not closed.

**Comment by xqq** [comment]
Referenced from the sample code in MSDN

https://msdn.microsoft.com/en-us/library/windows/desktop/ms706765(v=vs.85).aspx

which didn't call `WlanCloseHandle `
